databases:
  - name: natursurdb
    plan: free
    databaseName: natursur
    user: natursur

services:
  - type: web
    plan: free
    name: natursur
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'cd /opt/render/project/src/natursur && gunicorn natursur.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: natursurdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4