databases:
  - name: natursurdb
    plan: free
    databaseName: natursur
    user: natursur

services:
  - type: web
    plan: free
    name: natursur
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn natursur.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: natursurdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4